using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using FastTrack.Services.Interfaces;

namespace FastTrack.ViewModels;

/// <summary>
/// Static-content page for privacy posture, terms, and the medical disclaimer.
/// Kept as a real ViewModel (rather than pure XAML) so the copy is testable
/// and the Back command stays uniform with every other page.
/// </summary>
public partial class PrivacyViewModel : ObservableObject
{
    private readonly INavigationService _navigation;

    public PrivacyViewModel(INavigationService navigation)
    {
        _navigation = navigation;
    }

    public string LastUpdatedDisplay => "Last updated · May 2026";
    public string VersionText => "Fast Track 0.1.0 · local-only";

    public string Intro =>
        "Fast Track is built privacy-first. Your fasts, weights, moods, water and badges live on this device only. " +
        "There are no accounts, no servers, and no third-party trackers.";

    public string LocalOnlyBody =>
        "Everything you log is stored in an encrypted SQLite database inside Fast Track's private app sandbox on your phone. " +
        "Nothing is uploaded to a server, shared with us, or sold to anyone — because there is no server in the loop.";

    public string WhatWeCollectBody =>
        "We collect nothing. The app itself has no analytics SDK, no crash reporting service, and no advertising identifier. " +
        "The data you see in History, Insights and Trophies was all generated by you, on this device, and never leaves it unless you choose to export it.";

    public string PermissionsBody =>
        "Fast Track only asks for permissions it actually uses:\n" +
        "  •  Notifications — to remind you about stage milestones and quiet hours. Local-only, scheduled by the OS.\n" +
        "  •  Storage — to write your export JSON to a location you pick when you tap “Export”.\n" +
        "  •  Vibration — a subtle pulse on long-press / swipe-to-delete. Off if your phone is in silent mode.";

    public string YourRightsBody =>
        "Because the data lives on your device, you have full control:\n" +
        "  •  Export — Settings → Data → Export creates a complete JSON snapshot you own.\n" +
        "  •  Import — restore from any previous export to move to a new phone.\n" +
        "  •  Reset — Settings → Data → Reset all data wipes every row from the database and returns you to onboarding.\n" +
        "Uninstalling Fast Track also removes the database with it.";

    public string MedicalBody =>
        "Fast Track is a personal logging tool, not a medical device. It does not diagnose, treat or prevent any condition. " +
        "Intermittent fasting may not be appropriate if you are pregnant or breastfeeding, under 18, managing diabetes, " +
        "have a history of disordered eating, or are taking medication that requires food. Please talk to a healthcare professional " +
        "before starting or changing a fasting routine.";

    public string TermsBody =>
        "By using Fast Track you agree that the app is provided “as is”, without warranty of any kind. " +
        "You are responsible for your own health decisions and for keeping backups of your data via the Export feature. " +
        "Fast Track will not be liable for any loss arising from device failure, lost exports, or decisions you make based on the data shown. " +
        "These terms may be updated when the app is updated — the “Last updated” date above tells you when the copy was last revised.";

    [RelayCommand]
    private Task BackAsync() => _navigation.GoBackAsync();
}
